export const ERRORCODES = {
  UNKNOWN: '000',
  AUTH_INVALID_CREDENTALS: 100,
  AUTH_FAIL_SIGN_ACCESS_TOKEN: 102,
  AUTH_FAIL_SIGN_REFRESH_TOKEN: 103,
  AUTH_FAIL_VERIFY_ACCESS_TOKEN: 104,
  AUTH_FAIL_VERIFY_REFRESH_TOKEN: 105,

  DOCUMENT_FAIL_CREATE: 201,
  DOCUMENT_FAIL_UPDATE: 202,
  DOCUMENT_FAIL_DELETE: 203,
  DOCUMENT_FAIL_FIND: 204,
};
